"""add_platform_urls_to_creator_profiles

Revision ID: d63594d2b9b8
Revises: 004_add_webhook_events_table
Create Date: 2026-02-14 21:46:11.923945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd63594d2b9b8'
down_revision: Union[str, None] = '004_add_webhook_events_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('creator_profiles', sa.Column('platform_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Platform URLs: {YouTube: url, Twitter: url, ...}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('creator_profiles', 'platform_urls')
    # ### end Alembic commands ###
